version: "3.4"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    # MongoDB crash with permission denied errors if the command is not overridden like this
    command: bash -c 'chown -R mongodb:mongodb /data && chmod -R 755 /data && mongod'
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: magpie
      POSTGRES_USER: magpie
    restart: always

  magpie:
    image: pavics/magpie:latest
    container_name: magpie
    volumes:
      - ./config/magpie/magpie.ini:/opt/local/src/magpie/config/magpie.ini
    environment:
      FORWARDED_ALLOW_IPS: "*"
      MAGPIE_CONFIG_PATH: /config.yml
      # Need to comment the magpie.url in the magpie ini file as it has precedence over this variable
      MAGPIE_SECRET: itzaseekrit
      MAGPIE_ADMIN_GROUP: administrators
      MAGPIE_ADMIN_USER: $MAGPIE_ADMIN_USER
      MAGPIE_ADMIN_PASSWORD: $MAGPIE_ADMIN_PASSWORD
      MAGPIE_USER_GROUP: users
      MAGPIE_ANONYMOUS_USER: anonymous
      MAGPIE_PORT: 2001
      MAGPIE_LOG_LEVEL: INFO
      TWITCHER_PROTECTED_PATH: /twitcher/ows/proxy
      POSTGRES_USER: magpie
      POSTGRES_PASSWORD: qwerty
      POSTGRES_PORT: 5432
      POSTGRES_DB: magpie
      MAGPIE_POSTGRES_USERNAME: magpie
      MAGPIE_POSTGRES_PASSWORD: qwerty
      MAGPIE_POSTGRES_DB: magpie
      MAGPIE_POSTGRES_PORT: 5432
    restart: always

  geoserver:
    image: kartoza/geoserver:2.19.0
    container_name: geoserver
    restart: on-failure
    volumes:
      - $WORKSPACE_DIR:/user_workspaces
    environment:
      - GEOSERVER_DATA_DIR=/opt/footprints_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_USER=$GEOSERVER_ADMIN
      - GEOSERVER_ADMIN_PASSWORD=$GEOSERVER_PASSWORD
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
    depends_on:
      - geoserver-db
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  geoserver-db:
    image: kartoza/postgis:13-3.1
    container_name: geoserver-db
    environment:
      - POSTGRES_DB=gis,gwc
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=FALSE
    restart: on-failure
    healthcheck:
      test: "exit 0"
