#!/bin/bash

CUR_DIR=$(dirname "$0")
# set by DockerHub auto-build
DOCKER_TAG=${DOCKER_TAG:-latest}

echo "=> Information of Cowbird images to build (docker tag: $DOCKER_TAG)"
make -C "${CUR_DIR}/../.." APP_VERSION="${DOCKER_TAG}" docker-info

echo "=> Building variations of Cowbird images (docker tag: $DOCKER_TAG)"
make -C "${CUR_DIR}/../.." APP_VERSION="${DOCKER_TAG}" docker-build
