services:
  Magpie:
    active: true
    url: https://${HOSTNAME}/magpie
  Geoserver:
    active: true
    url: https://${HOSTNAME}/twitcher/ows/proxy/geoserver
  Catalog:
    active: false
    url: https://${HOSTNAME}/twitcher/ows/proxy/catalog
  Thredds:
    active: true
  Nginx:
    active: true

sync_permissions:
  user_workspace:
    services:
      Geoserver: /api/workspaces/private/
      Thredds: /catalog/birdhouse/workspaces/private/
    permissions_mapping:
      - Geoserver:
          - read
        Thredds:
          - read
          - browse
      - Geoserver:
          - write
        Thredds:
          - execute
