## Combined configuration definition to setup objects at Cowbird startup
## See documentation 'Configuration'

# [Required] Definition of managed services by Cowbird.
#
# services:
# ---------
#   [Required] Definition of managed services by Cowbird. Each service is provided as string that must match an actual
#   implementation in Cowbird. Each service must be further configured with one or more of the following parameters. If
#   a required parameter is missing for a service it will throw a `ServiceConfigurationException` exception.
#
#   service:
#     active:             [optional, default=False] bool allowing to deactivate a service and stop managing it
#     priority:           [optional, default=math.inf] Relative priority between services while handling events
#                         Lower values have higher priority, default value is last
#     url:                [optional, default=None] URI of the web service represented by this Cowbird service.
#                         Some Cowbird services do not represent web service, but other will throw an exception if
#                         missing.
#     workspace_dir:      [optional, default=None] Location of the users workspace root.
#                         Required for the following services : FileSystem, Catalog and Geoserver
#
services:
  Magpie:
    active: true
    url: https://${HOSTNAME}/magpie
  Geoserver:
    active: true
    url: http://${HOSTNAME}:8765/geoserver
    workspace_dir: ${WORKSPACE_DIR}
    admin_user: ${GEOSERVER_ADMIN}
    admin_password: ${GEOSERVER_PASSWORD}
  Catalog:
    active: true
    url: https://${HOSTNAME}/twitcher/ows/proxy/catalog
    workspace_dir: ${WORKSPACE_DIR}
  Thredds:
    active: true
  Nginx:
    active: true
  FileSystem:
    active: true
    priority: 1
    workspace_dir: ${WORKSPACE_DIR}

# [Required] This section defines how to synchronize permissions between services when they shared resources
sync_permissions:
  # Friendly name to identify a sync point (The value is not used by Cowbird so this can be any relevant keyword)
  user_workspace:
    # [Required] This section defines a list of services (referring to the service name of the 'services' section)
    # sharing resources
    services: # Every service sharing the same resources can be added in this list
      Geoserver: # Service name, which should also be found in the services list at the top of this file
        Geoserver_workspace: # <Resource root key> : <List of each segment of the resource path, with their name and type>
          - name: api
            type: service
          - name: workspaces
            type: workspace
          - name: private
            type: workspace
          - name: "**"
            type: workspace
      Thredds:
        Thredds_workspace:
          - name: catalog
            type: service
          - name: birdhouse
            type: folder
          - name: workspaces
            type: folder
          - name: private
            type: folder
          - name: "**"
            type: folder
          - name: "*"
            type: file
    # [Required] This section defines an array of permissions mapping between services
    # In this example, for every Geoserver_workspace's `read` permission, a `read` and `browse`
    # permissions will be created in Thredds_workspace.
    # If a `browse` permission is created in Thredds_workspace a `read` permission
    # will be added to `Geoserver_workspace`.
    permissions_mapping:
      - Geoserver_workspace: # 1st mapping between Geoserver_workspace:[read] and Thredds_workspace:[read,browse]
          - read
        Thredds_workspace:
          - read
          - browse
      - Geoserver_workspace: # 2nd mapping between Geoserver_workspace:[write] and Thredds_workspace:[execute]
          - write
        Thredds_workspace:
          - execute
