components:
  Magpie:
    active: true
    url: https://${HOSTNAME}/magpie
  Geoserver:
    active: true
    url: https://${HOSTNAME}/twitcher/ows/proxy/geoserver
  Catalog:
    active: false
    url: https://${HOSTNAME}/twitcher/ows/proxy/catalog
  Thredds:
    active: true
  Nginx:
    active: true

synch_permissions:
  user_workspace:
    services:
      geoserver: /api/workspaces/private/*
      thredds: /catalog/birdhouse/workspaces/private/*
    permissions_mapping:
      - geoserver:
          - read
        thredds:
          - read
          - browse
      - geoserver:
          - write
        thredds:
          - execute
