# look for secrets pushed by mistake

# NOTE: To fix problematic commits that got references to detected secrets, execute the following:
# 1. Assuming the branch is built on top of master for a PR
#     >> git rebase -i master
# 2. Then, replace "pick" by "squash" for matched problematic commits
#	 If this didn't work, more advanced edit of history commits needs to be applied.
#	 Please refer to git interactive rebase documentation to do so.
# 3. Finally re-run secrets analysis to validate that problems where fixed


name: Secret Scan
on:
  - pull_request
  - push

jobs:
  #trufflehog:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@master
  #  - name: trufflehog-actions-scan
  #    uses: edplato/trufflehog-actions-scan@master
    #- uses: max/secret-scan@master
    #  with:
    #    repo-token: "${{ secrets.GITHUB_TOKEN }}"

  # ref: https://github.com/svdarren/secrets-workflow/blob/9633bc1195a1ca1d4d70415aa4eff6cf55d706de/.github/workflows/secrets.yml
  gitleak:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install dependencies
        run: docker pull zricethezav/gitleaks

      - uses: gitleaks/gitleaks-action@v1.6.0  # see: https://github.com/gitleaks/gitleaks-action/issues/57
